[package]
name = "stegos_node"
version = "0.1.0"
authors = ["Stegos AG <info@stegos.cc>"]
build = "build.rs"
edition = "2018"

[dependencies]
stegos_config = { path = "../config" }
stegos_consensus = { path = "../consensus" }
stegos_crypto = { path = "../crypto" }
stegos_blockchain = { path = "../blockchain" }
stegos_network = { path = "../network" }
stegos_keychain = { path = "../keychain" }

log = "0.4"
lazy_static = "1.1"
failure = "0.1"
futures = "0.1"
futures-stream-select-all-send = "0.1"
tokio-timer = "0.2"
chrono = "0.4"
protobuf = "2.2"
serde = "1.0"
serde_derive = "1.0"
rand = "0.6"
rand_isaac = "0.1.1"
simple_logger = "1.0"
clap = "2.32"
bitvector = "0.1"
linked-hash-map = "0.5"

[dev-dependencies]
stegos_wallet = { path = "../wallet" }

[build-dependencies]
protobuf-codegen-pure = "2.2"

[[bin]]
name = "bootstrap"
path = "src/bootstrap.rs"
